name: Docker Image

on:
  push:
    branches:
      - master

jobs:
  vet:
    name: "go vet"
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run go vet
        run: go vet github.com/wavy-cat/petpet-go/cmd/app

  test:
    name: "go test"
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run go test
        run: go test ./...

  build:
    name: "Build and Push"
    runs-on: ubuntu-24.04-arm
    needs: [ vet, test ]
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/wavy-cat/petpet-go:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max